my_website/my_website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from resume import views

urlpatterns = [
    url(r'^$', views.user_login, name='user_login'),
    url(r'^resume/', include('resume.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    #url(r'^logout/$', views.user_logout, name = 'logout'),
    #url(r'special/', views.special, name = 'special' ),
]

my_website/resume/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from resume import views

app_name = 'resume'

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^resume/', views.show_resume, name='show_resume'),

]

my_website/resume/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.PROTECT)

    #additional classes

    first_name = models.CharField(blank=True, max_length=100)
    last_name = models.CharField(blank=True, max_length=100)
    email = models.EmailField()
    text = models.CharField(max_length=10000)



    def __str__(self):
        return self.user.username

my_website/resume/forms.py
from django import forms
from django.contrib.auth.models import User
from resume.models import UserProfileInfo
from django.core import validators


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    verify_email = forms.EmailField(label='Verify Email: ')
    text = forms.CharField(widget=forms.Textarea, required=True)
    botcatcher = forms.CharField(required=False,
                                    widget=forms.HiddenInput,
                                    validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('verify email')


    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

my_website/resume/views.py
from django.shortcuts import render
#from resume.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
import os
import smtplib,ssl
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders
# Create your views here.


def index(request):

        return render(request, 'resume/index.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'resume/logout.html')



@login_required
def show_resume(request):

    if request.method == 'POST':
        first = request.POST.get('lastname')
        last = request.POST.get('firstname')
        email = request.POST.get('email')
        company = request.POST.get('company')
        comment = request.POST.get('comment')

        send_from = 'vetautoreport@gmail.com'
        send_to =   'jacobcansler@gmail.com'
        subject = 'Webisite Comment'
        text = 'Name: '+ first + ' ' + last+ '\ncompany: ' + company + '\nComments: '+ comment +'\nEmail:  ' +email
        port= 465
        server = 'smtp.gmail.com'
        username='vetautoreport@gmail.com'
        password=''

        print('Name: '+ first + ' ' + last+ '\ncompany: ' + company + '\nComments: '+ comment +'\nEmail:  ' +email)

        isTls=True


        msg = MIMEMultipart()
        msg['From'] = send_from
        msg['To'] = send_to
        msg['Date'] = formatdate(localtime = True)
        msg['Subject'] = subject
        msg.attach(MIMEText(text))

        smtp = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        smtp.login(username,password)
        smtp.sendmail(send_from, send_to, msg.as_string())
        smtp.close()
        print('e-mail sent!')

    return render(request, 'resume/resume.html')

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                #return HttpResponseRedirect(reverse('show_resume'))
                return render(request, 'resume/resume.html')
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("someone tried to login and failed")
            print("username:{}".format(username))
            return HttpResponse("invalid login")

    else:
        return render(request, 'resume/index.html')

my_website/templates/resume/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "resume/CSS/main_page.css" %}"/>
    <script>
    src="https://code.jquery.com/jquery-3.2.1.js"
    integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    crossorigin="anonymous">
    </script>
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav id="nav" class="navbar navbar-default navbar-fixed-top navbar-inverse">

      <!-- <div class="container"> -->

        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'resume:show_resume' %}" >Welcome</a>
          </div>

          <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
              <li><a href="#aboutme">About Me</a></li>
              <li><a href="#careers">Resume</a></li>
              <li><a href="#skillz">Skills</a></li>
                <li><a href="#commentzone">Comments</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'user_login' %}">Login</a></li>
              {% endif %}
            </ul>


              <!-- Clock Nav Bar (better if i put in js file?)-->

          <ul id="nav "class="nav navbar-nav navbar-right">
          <li><a href="E:\code\My_Website\main_page.html"><div id="clockbox"></div>

                    <script type="text/javascript">
                    var tday=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
                    var tmonth=["January","February","March","April","May","June","July","August","September","October","November","December"];

                    function GetClock(){
                    var d=new Date();
                    var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getFullYear();
                    var nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

                    if(nhour==0){ap=" AM";nhour=12;}
                    else if(nhour<12){ap=" AM";}
                    else if(nhour==12){ap=" PM";}
                    else if(nhour>12){ap=" PM";nhour-=12;}

                    if(nmin<=9) nmin="0"+nmin;
                    if(nsec<=9) nsec="0"+nsec;

                    var clocktext=""+tday[nday]+", "+tmonth[nmonth]+" "+ndate+", "+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
                    document.getElementById('clockbox').innerHTML=clocktext;
                    }

                    GetClock();
                    setInterval(GetClock,1000);
            </script></a></li>

      </ul>
      <!-- </div> -->
    </nav>

      {% block body_block %}

      {% endblock %}




  </body>
</html>

my_website/templates/resume/index.html
<!DOCTYPE html>

{% extends "resume/base.html" %}
{% load staticfiles %}

  {% block body_block %}
<link rel="stylesheet" href="{% static "resume/CSS/main_page.css" %}"/>

<div class="jumbotron">

  <h1>Please Login</h1>

  <form enctype="multipart/form-data" action="" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter username">

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="password">

    <input type="submit" name="" value="Login">
  </form>

</div>

  {% endblock %}

my_website/templates/resume/logout.html
<!DOCTYPE html>

{% extends "resume/base.html" %}
{% load staticfiles %}

  {% block body_block %}
<link rel="stylesheet" href="{% static "resume/CSS/main_page.css" %}"/>

<div class="jumbotron">

  <h1>Thank you for visiting!</h1>

</div>
  {% endblock %}